TASK12:
  name: NLVR2
  type: VL-binary-classifier
  num_labels: 2
  loss: BCEWithLogitLoss
  process: nlvr
  task_id: 12
  dataroot: Multilingual_Visual_Reasoning/data/en/annotations
  features_h5path1: Multilingual_Visual_Reasoning/data/en/nlvr2_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: Multilingual_Visual_Reasoning/data/en/annotations_json/train.json
  val_annotations_jsonpath: Multilingual_Visual_Reasoning/data/en/annotations_json/dev.json
  max_seq_length: 80
  max_region_num: 36
  batch_size: 64
  eval_batch_size: 512
  train_split: train
  val_split: dev
  lr: 0.00001
  num_epoch: 20
